name: Busq CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches:
      - '*'
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run Tests
        run: swift test -v

  ci-ios:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: xcrun swift build
      - name: Run Tests
        run: |
          sed -i '' 's/let excludeCLI = false/let excludeCLI = true/' Package.swift
          xcodebuild test -configuration Debug -scheme "Busq" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 13"

  ci-linux:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run Tests
        run: swift test -v

  ci-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.5-release
          tag: 5.5-RELEASE
      - name: Build
        run: swift build -v
      - name: Run Tests
        run: swift test -v

