name: Busq CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches:
      - '*'
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  ci-macos:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: xcrun swift test
 
      - name: Test iOS
        run: xcodebuild test -configuration Debug -scheme "Busq" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 13"

  ci-linux:
    runs-on: ubuntu-latest 

    steps:
      - name: Get swift version
        run: swift --version 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: xcrun swift test


